---
- name: Load OS specific values
  include_vars: "{{ ansible_os_family }}.yml"
  with_first_found:
   - "{{ ansible_distribution }}.yml"
   - "{{ ansible_os_family }}.yml"
   - default.yml

- include: add_groups.yml

- include: users.yml

- include: remove_groups.yml

- include: default_ssh_key.yml

- include: additional_ssh_keys.yml
  with_items: "{{ users }}"
  when: >
    user_item.install_additional_ssh_keys is defined and
    user_item.install_additional_ssh_keys == true
  loop_control:
    loop_var: user_item

- include: ssh_keys.yml

- include: sudo.yml
